POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "manager.john@futurefocus.com",
    "password": "secret246",
    "role": "manager",
    "department": "Legal"
}

###

POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "name": "David Brown",
    "email": "admin.david@futurefocus.com",
    "password": "dbrown456",
    "role": "admin",
    "department": "IT"
  }

###

POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "name": "Sipho Mciwa",
  "email": "sipho@futurefocus.com",
  "password": "test-pass321",
  "role": "employee",
  "department": "IT"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "david_brown@example.com",
    "password": "dbrown456"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "sipho@futurefocus.com",
    "password": "test-pass321"
}


###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "john@company.com",
    "password": "secret246"
}

